name: API Test Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    # Runs twice: daily at 2 AM UTC and Monday/Thursday at 2 PM UTC
    - cron: '0 14 * * *'     # Daily at 2 AM UTC
    - cron: '0 03 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Execute Tests
      run: mvn clean test -Dsuite=testng
